#include "common.hpp"
#include "natives.hpp"
#include "script.hpp"
#include "fiber_pool.hpp"
#include "local_player.hpp"
#include "gta/enums.hpp"
#include "script_global.hpp"

using namespace big;

namespace helper
{
	// example: set_packed_bool(31736, 1)
	/*
	HUD::CLEAR_HELP(true);
	func_799("BURIED_OUTHEL2", -1);
	HUD::BEGIN_TEXT_COMMAND_THEFEED_POST("BURIED_OUTTIC");
	HUD::END_TEXT_COMMAND_THEFEED_POST_UNLOCK_TU("CLOTHES_UNLOCK", 7, "BURIED_OUTHEL", 1);
	func_19945(31736, 1, -1, 1);
	*/
	static BOOL set_packed_bool(int index, BOOL value)
	{
		int iParam0 = index; // index
		BOOL bParam1 = value; // value
		int iParam2 = 0xFFFFFFFF; // character_index
		BOOL bParam3 = 1; // save

		BOOL bVar0;
		int iVar1;
		int iVar2;
		int iVar3;
		int iVar4;
		int iVar5;
		int iVar6;
		int iVar7;
		int iVar8;
		int iVar9;
		int iVar10;
		int iVar11;
		int iVar12;
		int iVar13;
		int iVar14;
		int iVar15;
		int iVar16;
		int iVar17;
		int iVar18;
		int iVar19;
		int iVar20;
		int iVar21;
		int iVar22;
		int iVar23;
		int iVar24;
		int iVar25;
		int iVar26;

		if (iParam2 == 0xFFFFFFFF)
		{
			iParam2 = g_local_player.character_index;
		}
		bVar0 = false;
		if (iParam0 >= 0 && iParam0 < 192)
		{
			iVar2 = STATS::GET_PACKED_BOOL_STAT_KEY((iParam0 - 0), false, true, iParam2);
			iVar1 = ((iParam0 - 0) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 0)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar2, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 192 && iParam0 < 384)
		{
			iVar3 = STATS::GET_PACKED_BOOL_STAT_KEY((iParam0 - 192), true, true, iParam2);
			iVar1 = ((iParam0 - 192) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 192)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar3, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 513 && iParam0 < 705)
		{
			iVar4 = STATS::GET_PACKED_BOOL_STAT_KEY((iParam0 - 513), false, false, 0);
			iVar1 = ((iParam0 - 513) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 513)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar4, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 705 && iParam0 < 1281)
		{
			iVar5 = STATS::GET_PACKED_BOOL_STAT_KEY((iParam0 - 705), true, false, 0);
			iVar1 = ((iParam0 - 705) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 705)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar5, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 3111 && iParam0 < 3879)
		{
			iVar6 = STATS::GET_PACKED_TU_BOOL_STAT_KEY((iParam0 - 3111), false, true, iParam2);
			iVar1 = ((iParam0 - 3111) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 3111)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar6, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 2919 && iParam0 < 3111)
		{
			iVar7 = STATS::GET_PACKED_TU_BOOL_STAT_KEY((iParam0 - 2919), false, false, 0);
			iVar1 = ((iParam0 - 2919) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 2919)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar7, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 4207 && iParam0 < 4335)
		{
			iVar8 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 4207), false, true, iParam2, "_NGPSTAT_BOOL");
			iVar1 = ((iParam0 - 4207) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 4207)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar8, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 4335 && iParam0 < 4399)
		{
			iVar9 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 4335), false, false, 0, "_NGPSTAT_BOOL");
			iVar1 = ((iParam0 - 4335) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 4335)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar9, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 6029 && iParam0 < 6413)
		{
			iVar10 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 6029), false, true, iParam2, "_NGTATPSTAT_BOOL");
			iVar1 = ((iParam0 - 6029) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 6029)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar10, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 7385 && iParam0 < 7641)
		{
			iVar11 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 7385), false, true, iParam2, "_NGDLCPSTAT_BOOL");
			iVar1 = ((iParam0 - 7385) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 7385)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar11, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 7321 && iParam0 < 7385)
		{
			iVar12 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 7321), false, false, 0, "_NGDLCPSTAT_BOOL");
			iVar1 = ((iParam0 - 7321) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 7321)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar12, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 9361 && iParam0 < 9553)
		{
			iVar13 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 9361), false, true, iParam2, "_DLCBIKEPSTAT_BOOL");
			iVar1 = ((iParam0 - 9361) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 9361)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar13, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 15369 && iParam0 < 15561)
		{
			iVar14 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 15369), false, true, iParam2, "_DLCGUNPSTAT_BOOL");
			iVar1 = ((iParam0 - 15369) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 15369)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar14, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 15562 && iParam0 < 15946)
		{
			iVar15 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 15562), false, true, iParam2, "_GUNTATPSTAT_BOOL");
			iVar1 = ((iParam0 - 15562) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 15562)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar15, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 15946 && iParam0 < 16010)
		{
			iVar16 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 15946), false, true, iParam2, "_DLCSMUGCHARPSTAT_BOOL");
			iVar1 = ((iParam0 - 15946) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 15946)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar16, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 18098 && iParam0 < 18162)
		{
			iVar17 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 18098), false, true, iParam2, "_GANGOPSPSTAT_BOOL");
			iVar1 = ((iParam0 - 18098) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 18098)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar17, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 22066 && iParam0 < 22194)
		{
			iVar18 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 22066), false, true, iParam2, "_BUSINESSBATPSTAT_BOOL");
			iVar1 = ((iParam0 - 22066) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 22066)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar18, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 24962 && iParam0 < 25538)
		{
			iVar19 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 24962), false, true, iParam2, "_ARENAWARSPSTAT_BOOL");
			iVar1 = ((iParam0 - 24962) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 24962)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar19, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 26810 && iParam0 < 27258)
		{
			iVar20 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 26810), false, true, iParam2, "_CASINOPSTAT_BOOL");
			iVar1 = ((iParam0 - 26810) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 26810)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar20, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 28098 && iParam0 < 28354)
		{
			iVar21 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 28098), false, true, iParam2, "_CASINOHSTPSTAT_BOOL");
			iVar1 = ((iParam0 - 28098) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 28098)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar21, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 28355 && iParam0 < 28483)
		{
			iVar22 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 28355), false, true, iParam2, "_HEIST3TATTOOSTAT_BOOL");
			iVar1 = ((iParam0 - 28355) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 28355)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar22, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 30227 && iParam0 < 30355)
		{
			iVar23 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 30227), false, true, iParam2, "_SU20PSTAT_BOOL");
			iVar1 = ((iParam0 - 30227) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 30227)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar23, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 30355 && iParam0 < 30483)
		{
			iVar24 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 30355), false, true, iParam2, "_SU20TATTOOSTAT_BOOL");
			iVar1 = ((iParam0 - 30355) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 30355)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar24, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 30515 && iParam0 < 30707)
		{
			iVar25 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 30515), false, true, iParam2, "_HISLANDPSTAT_BOOL");
			iVar1 = ((iParam0 - 30515) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 30515)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar25, bParam1, iVar1, bParam3);
		}
		else if (iParam0 >= 31707 && iParam0 < 32283)
		{
			iVar26 = STATS::_GET_NGSTAT_BOOL_HASH((iParam0 - 31707), false, true, iParam2, "_TUNERPSTAT_BOOL");
			iVar1 = ((iParam0 - 31707) - STATS::_STAT_GET_PACKED_BOOL_MASK((iParam0 - 31707)) * 64);
			bVar0 = STATS::STAT_SET_BOOL_MASKED(iVar26, bParam1, iVar1, bParam3);
		}
		return bVar0;
	}

	static BOOL set_packed_int(int index, int value)
	{
		int iParam0 = index; // index
		int iParam1 = value; // value
		int iParam2 = 0xFFFFFFFF; // character_index
		BOOL bParam3 = 1; // save

		int iVar0;
		int iVar1;
		bool bVar2;

		if (iParam2 == 0xFFFFFFFF)
		{
			iParam2 = g_local_player.character_index;
		}
		if (iParam1 < 0)
		{
			iParam1 = 255;
		}
		iVar0 = 0;
		iVar1 = 0;
		if (iParam0 >= 384 && iParam0 < 457)
		{
			iVar0 = STATS::GET_PACKED_INT_STAT_KEY((iParam0 - 384), false, true, iParam2);
			iVar1 = ((iParam0 - 384) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 384)) * 8) * 8;
		}
		else if (iParam0 >= 457 && iParam0 < 513)
		{
			iVar0 = STATS::GET_PACKED_INT_STAT_KEY((iParam0 - 457), true, true, iParam2);
			iVar1 = ((iParam0 - 457) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 457)) * 8) * 8;
		}
		else if (iParam0 >= 1281 && iParam0 < 1305)
		{
			iVar0 = STATS::GET_PACKED_INT_STAT_KEY((iParam0 - 1281), false, false, 0);
			iVar1 = ((iParam0 - 1281) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 1281)) * 8) * 8;
		}
		else if (iParam0 >= 1305 && iParam0 < 1361)
		{
			iVar0 = STATS::GET_PACKED_INT_STAT_KEY((iParam0 - 1305), true, false, 0);
			iVar1 = ((iParam0 - 1305) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 1305)) * 8) * 8;
		}
		else if (iParam0 >= 1393 && iParam0 < 2919)
		{
			iVar0 = STATS::GET_PACKED_TU_INT_STAT_KEY((iParam0 - 1393), false, true, iParam2);
			iVar1 = ((iParam0 - 1393) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 1393)) * 8) * 8;
		}
		else if (iParam0 >= 1361 && iParam0 < 1393)
		{
			iVar0 = STATS::GET_PACKED_TU_INT_STAT_KEY((iParam0 - 1361), false, false, 0);
			iVar1 = ((iParam0 - 1361) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 1361)) * 8) * 8;
		}
		else if (iParam0 >= 3879 && iParam0 < 4143)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 3879), false, true, iParam2, "_NGPSTAT_INT");
			iVar1 = ((iParam0 - 3879) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 3879)) * 8) * 8;
		}
		else if (iParam0 >= 4143 && iParam0 < 4207)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 4143), false, false, 0, "_NGPSTAT_INT");
			iVar1 = ((iParam0 - 4143) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 4143)) * 8) * 8;
		}
		else if (iParam0 >= 4399 && iParam0 < 6028)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 4399), false, true, iParam2, "_LRPSTAT_INT");
			iVar1 = ((iParam0 - 4399) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 4399)) * 8) * 8;
		}
		else if (iParam0 >= 6413 && iParam0 < 7262)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 6413), false, true, iParam2, "_APAPSTAT_INT");
			iVar1 = ((iParam0 - 6413) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 6413)) * 8) * 8;
		}
		else if (iParam0 >= 7262 && iParam0 < 7313)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 7262), false, true, iParam2, "_LR2PSTAT_INT");
			iVar1 = ((iParam0 - 7262) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 7262)) * 8) * 8;
		}
		else if (iParam0 >= 7681 && iParam0 < 9361)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 7681), false, true, iParam2, "_BIKEPSTAT_INT");
			iVar1 = ((iParam0 - 7681) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 7681)) * 8) * 8;
		}
		else if (iParam0 >= 9553 && iParam0 < 15265)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 9553), false, true, iParam2, "_IMPEXPPSTAT_INT");
			iVar1 = ((iParam0 - 9553) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 9553)) * 8) * 8;
		}
		else if (iParam0 >= 15265 && iParam0 < 15369)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 15265), false, true, iParam2, "_GUNRPSTAT_INT");
			iVar1 = ((iParam0 - 15265) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 15265)) * 8) * 8;
		}
		else if (iParam0 >= 16010 && iParam0 < 18098)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 16010), false, true, iParam2, "_DLCSMUGCHARPSTAT_INT");
			iVar1 = ((iParam0 - 16010) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 16010)) * 8) * 8;
		}
		else if (iParam0 >= 18162 && iParam0 < 19018)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 18162), false, true, iParam2, "_GANGOPSPSTAT_INT");
			iVar1 = ((iParam0 - 18162) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 18162)) * 8) * 8;
		}
		else if (iParam0 >= 19018 && iParam0 < 22066)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 19018), false, true, iParam2, "_BUSINESSBATPSTAT_INT");
			iVar1 = ((iParam0 - 19018) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 19018)) * 8) * 8;
		}
		else if (iParam0 >= 22194 && iParam0 < 24962)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 22194), false, true, iParam2, "_ARENAWARSPSTAT_INT");
			iVar1 = ((iParam0 - 22194) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 22194)) * 8) * 8;
		}
		else if (iParam0 >= 25538 && iParam0 < 26810)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 25538), false, true, iParam2, "_CASINOPSTAT_INT");
			iVar1 = ((iParam0 - 25538) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 25538)) * 8) * 8;
		}
		else if (iParam0 >= 27258 && iParam0 < 28098)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 27258), false, true, iParam2, "_CASINOHSTPSTAT_INT");
			iVar1 = ((iParam0 - 27258) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 27258)) * 8) * 8;
		}
		else if (iParam0 >= 28483 && iParam0 < 30227)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 28483), false, true, iParam2, "_SU20PSTAT_INT");
			iVar1 = ((iParam0 - 28483) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 28483)) * 8) * 8;
		}
		else if (iParam0 >= 30483 && iParam0 < 30515)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 30483), false, true, iParam2, "_HISLANDPSTAT_INT");
			iVar1 = ((iParam0 - 30483) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 30483)) * 8) * 8;
		}
		else if (iParam0 >= 30707 && iParam0 < 31707)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 30707), false, true, iParam2, "_TUNERPSTAT_INT");
			iVar1 = ((iParam0 - 30707) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 30707)) * 8) * 8;
		}
		else if (iParam0 >= 7641 && iParam0 < 7681)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 7641), false, true, iParam2, "_NGDLCPSTAT_INT");
			iVar1 = ((iParam0 - 7641) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 7641)) * 8) * 8;
		}
		else if (iParam0 >= 7313 && iParam0 < 7321)
		{
			iVar0 = STATS::_GET_NGSTAT_INT_HASH((iParam0 - 7313), false, false, 0, "_NGDLCPSTAT_INT");
			iVar1 = ((iParam0 - 7313) - STATS::_STAT_GET_PACKED_INT_MASK((iParam0 - 7313)) * 8) * 8;
		}
		bVar2 = STATS::STAT_SET_MASKED_INT(iVar0, iParam1, iVar1, 8, bParam3);
		return bVar2;
	}

	static void set_mass_packed_bool(BOOL value, int32_t min_i, int32_t max_i)
	{
		LOG(INFO) << fmt::format("Started. {}, {}, {}", value, min_i, max_i);
		for (auto index = min_i; index <= max_i; index++)
		{
			set_packed_bool(index, value);
		}
		LOG(INFO) << fmt::format("Done. {}, {}, {}\n", value, min_i, max_i);
	}

	static int get_rp_value(int value)
	{
		return *script_global(293361).at((value + 1)).as<int*>();
	}

	static void bool_unlocks()
	{
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_MELEECHLENGECOMPLETED"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_HEADSHOTCHLENGECOMPLETED"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_COMPLET_HEIST_MEM"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_COMPLET_HEIST_1STPER"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_FLEECA_FIN"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_HST_ORDER"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_HST_SAME_TEAM"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_HST_ULT_CHAL"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_HUMANE_FIN"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_PACIFIC_FIN"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_PRISON_FIN"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_SERIESA_FIN"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_IAA"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_SUBMARINE"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_MISSILE"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_SUPPORT"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_LOYALTY2"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_LOYALTY3"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_CRIMMASMD2"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_CRIMMASMD3"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_ALLINORDER"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_LOYALTY"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_CRIMMASMD"), TRUE, TRUE);
		if (g_local_player.character_index == MP0)
		{
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_INTELGATHER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COMPOUNDINFILT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_LOOT_FINDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MAX_DISRUPT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_THE_ISLAND_HEIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GOING_ALONE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TEAM_WORK"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MIXING_UP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PRO_THIEF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CAT_BURGLAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ONE_OF_THEM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GOLDEN_GUN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELITE_THIEF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PROFESSIONAL"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_HELPING_OUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COURIER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PARTY_VIBES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_HELPING_HAND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELEVENELEVEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_VCM_FLOW_CS_RSC_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_VCM_FLOW_CS_BWL_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_VCM_FLOW_CS_MTG_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_VCM_FLOW_CS_OIL_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_VCM_FLOW_CS_DEF_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_VCM_FLOW_CS_FIN_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CAS_VEHICLE_REWARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_RACE_MODDED_CAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_DRIVE_RALLY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_GTA_RACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_BOAT_RACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_FOOT_RACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_TEAM_DM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_VEHICLE_DM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_MISSION_CONTACT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_A_PLAYLIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_POINT_TO_POINT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_ONE_ON_ONE_DM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_ONE_ON_ONE_RACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_SURV_A_BOUNTY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_SET_WANTED_LVL_ON_PLAY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_GANG_BACKUP_GANGS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_GANG_BACKUP_LOST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_GANG_BACKUP_VAGOS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_CALL_MERCENARIES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PHONE_MECH_DROP_CAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_GONE_OFF_RADAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_FILL_TITAN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_MOD_CAR_USING_APP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_BUY_APPARTMENT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_BUY_INSURANCE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_BUY_GARAGE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_ENTER_FRIENDS_HOUSE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_CALL_STRIPPER_HOUSE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_CALL_FRIEND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_SEND_FRIEND_REQUEST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_W_WANTED_PLAYER_TV"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_0"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_1"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_3"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_4"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_5"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_6"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_7"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_8"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_9"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIRST_TIME1"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIRST_TIME2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIRST_TIME3"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIRST_TIME4"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIRST_TIME5"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIRST_TIME6"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ALL_IN_ORDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SUPPORTING_ROLE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ACTIVATE_2_PERSON_KEY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ALL_ROLES_HEIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_LEADER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SURVIVALIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SCOPEOUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CREWEDUP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MOVINGON"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PROMOCAMP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GUNMAN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SMASHNGRAB"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_INPLAINSI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_UNDETECTED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ALLROUND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELITETHEIF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PRO"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SUPPORTACT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SHAFTED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COLLECTOR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_DEADEYE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PISTOLSATDAWN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TRAFFICAVOI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CANTCATCHBRA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_WIZHARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_APEESCAPE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MONKEYKIND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_AQUAAPE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_KEEPFAITH"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TRUELOVE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_NEMESIS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FRIENDZONED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_BUY_EVERY_GUN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_DAILYOBJMONTHBONUS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_DAILYOBJWEEKBONUS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_DRIVELESTERCAR5MINS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FINISH_HEIST_NO_DAMAGE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM25DIFFERENTDM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM25DIFFERENTRACES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM25DIFITEMSCLOTHES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMFURTHESTWHEELIE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM6DARTCHKOUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM_GOLF_HOLE_IN_1"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM_SHOOTRANG_GRAN_WON"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM_TENNIS_5_SET_WINS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMATTGANGHQ"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMFULLYMODDEDCAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMKILL3ANDWINGTARACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMKILLSTREAKSDM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMMOSTKILLSGANGHIDE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMMOSTKILLSSURVIVE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMPICKUPDLCCRATE1ST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMRACEWORLDRECHOLDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMTATTOOALLBODYPARTS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMWINALLRACEMODES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMWINCUSTOMRACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMWINEVERYGAMEMODE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SPLIT_HEIST_TAKE_EVENLY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_STORE_20_CAR_IN_GARAGES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_SR_TIER_1_REWARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_SR_TIER_3_REWARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_SR_INCREASE_THROW_CAP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CLUB_COORD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CLUB_HOTSPOT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CLUB_CLUBBER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_BEGINNER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIELD_FILLER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ARMCHAIR_RACER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_LEARNER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SUNDAY_DRIVER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_THE_ROOKIE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_BUMP_AND_RUN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GEAR_HEAD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_DOOR_SLAMMER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_HOT_LAP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ARENA_AMATEUR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PAINT_TRADER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SHUNTER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_JOCK"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_WARRIOR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_T_BONE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MAYHEM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_WRECKER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CRASH_COURSE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ARENA_LEGEND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PEGASUS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CONTACT_SPORT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_UNSTOPPABLE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_LOW_FLOW_CS_DRV_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_LOW_FLOW_CS_TRA_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_LOW_FLOW_CS_FUN_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_LOW_FLOW_CS_PHO_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_LOW_FLOW_CS_FIN_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_LOW_BEN_INTRO_CS_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SCOPEOUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CREWEDUP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MOVINGON"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PROMOCAMP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GUNMAN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SMASHNGRAB"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_INPLAINSI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_UNDETECTED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ALLROUND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELITETHEIF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PRO"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SUPPORTACT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SHAFTED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COLLECTOR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_DEADEYE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PISTOLSATDAWN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TRAFFICAVOI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CANTCATCHBRA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_WIZHARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_APEESCAPE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MONKEYKIND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_AQUAAPE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_KEEPFAITH"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TRUELOVE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_NEMESIS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FRIENDZONED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_INTELGATHER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COMPOUNDINFILT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_LOOT_FINDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MAX_DISRUPT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_THE_ISLAND_HEIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GOING_ALONE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TEAM_WORK"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MIXING_UP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PRO_THIEF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CAT_BURGLAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ONE_OF_THEM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GOLDEN_GUN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELITE_THIEF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PROFESSIONAL"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_HELPING_OUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COURIER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PARTY_VIBES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_HELPING_HAND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELEVENELEVEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_COMPLETE_H4_F_USING_VETIR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_COMPLETE_H4_F_USING_LONGFIN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_COMPLETE_H4_F_USING_ANNIH"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_COMPLETE_H4_F_USING_ALKONOS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_COMPLETE_H4_F_USING_PATROLB"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_FURIA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_MINITANK"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_YOSEMITE2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_ZHABA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_IMORGEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_SULTAN2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_VAGRANT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_VSTR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_STRYDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_SUGOI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_KANJO"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_FORMULA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_FORMULA2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_JB7002"), TRUE, TRUE);
		}
		else
		{
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_INTELGATHER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_COMPOUNDINFILT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_LOOT_FINDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_MAX_DISRUPT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_THE_ISLAND_HEIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_GOING_ALONE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_TEAM_WORK"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_MIXING_UP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PRO_THIEF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_CAT_BURGLAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ONE_OF_THEM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_GOLDEN_GUN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ELITE_THIEF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PROFESSIONAL"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_HELPING_OUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_COURIER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PARTY_VIBES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_HELPING_HAND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ELEVENELEVEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_VCM_FLOW_CS_RSC_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_VCM_FLOW_CS_BWL_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_VCM_FLOW_CS_MTG_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_VCM_FLOW_CS_OIL_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_VCM_FLOW_CS_DEF_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_VCM_FLOW_CS_FIN_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CAS_VEHICLE_REWARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_RACE_MODDED_CAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_DRIVE_RALLY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_PLAY_GTA_RACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_PLAY_BOAT_RACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_PLAY_FOOT_RACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_PLAY_TEAM_DM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_PLAY_VEHICLE_DM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_PLAY_MISSION_CONTACT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_PLAY_A_PLAYLIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_PLAY_POINT_TO_POINT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_PLAY_ONE_ON_ONE_DM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_PLAY_ONE_ON_ONE_RACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_SURV_A_BOUNTY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_SET_WANTED_LVL_ON_PLAY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_GANG_BACKUP_GANGS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_GANG_BACKUP_LOST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_GANG_BACKUP_VAGOS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_CALL_MERCENARIES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_PHONE_MECH_DROP_CAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_GONE_OFF_RADAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_FILL_TITAN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_MOD_CAR_USING_APP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_BUY_APPARTMENT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_BUY_INSURANCE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_BUY_GARAGE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_ENTER_FRIENDS_HOUSE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_CALL_STRIPPER_HOUSE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_CALL_FRIEND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_SEND_FRIEND_REQUEST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_CL_W_WANTED_PLAYER_TV"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_PILOT_ASPASSEDLESSON_0"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_PILOT_ASPASSEDLESSON_1"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_PILOT_ASPASSEDLESSON_2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_PILOT_ASPASSEDLESSON_3"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_PILOT_ASPASSEDLESSON_4"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_PILOT_ASPASSEDLESSON_5"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_PILOT_ASPASSEDLESSON_6"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_PILOT_ASPASSEDLESSON_7"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_PILOT_ASPASSEDLESSON_8"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_PILOT_ASPASSEDLESSON_9"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FIRST_TIME1"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FIRST_TIME2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FIRST_TIME3"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FIRST_TIME4"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FIRST_TIME5"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FIRST_TIME6"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ALL_IN_ORDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SUPPORTING_ROLE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ACTIVATE_2_PERSON_KEY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ALL_ROLES_HEIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_LEADER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SURVIVALIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SCOPEOUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_CREWEDUP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_MOVINGON"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PROMOCAMP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_GUNMAN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SMASHNGRAB"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_INPLAINSI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_UNDETECTED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ALLROUND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ELITETHEIF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PRO"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SUPPORTACT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SHAFTED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_COLLECTOR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_DEADEYE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PISTOLSATDAWN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_TRAFFICAVOI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_CANTCATCHBRA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_WIZHARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_APEESCAPE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_MONKEYKIND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_AQUAAPE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_KEEPFAITH"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_TRUELOVE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_NEMESIS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FRIENDZONED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_BUY_EVERY_GUN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_DAILYOBJMONTHBONUS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_DAILYOBJWEEKBONUS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_DRIVELESTERCAR5MINS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FINISH_HEIST_NO_DAMAGE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FM25DIFFERENTDM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FM25DIFFERENTRACES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FM25DIFITEMSCLOTHES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMFURTHESTWHEELIE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FM6DARTCHKOUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FM_GOLF_HOLE_IN_1"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FM_SHOOTRANG_GRAN_WON"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FM_TENNIS_5_SET_WINS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMATTGANGHQ"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMFULLYMODDEDCAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMKILL3ANDWINGTARACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMKILLSTREAKSDM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMMOSTKILLSGANGHIDE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMMOSTKILLSSURVIVE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMPICKUPDLCCRATE1ST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMRACEWORLDRECHOLDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMTATTOOALLBODYPARTS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMWINALLRACEMODES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMWINCUSTOMRACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FMWINEVERYGAMEMODE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SPLIT_HEIST_TAKE_EVENLY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_STORE_20_CAR_IN_GARAGES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_SR_TIER_1_REWARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_SR_TIER_3_REWARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_SR_INCREASE_THROW_CAP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_CLUB_COORD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_CLUB_HOTSPOT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_CLUB_CLUBBER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_BEGINNER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FIELD_FILLER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ARMCHAIR_RACER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_LEARNER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SUNDAY_DRIVER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_THE_ROOKIE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_BUMP_AND_RUN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_GEAR_HEAD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_DOOR_SLAMMER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_HOT_LAP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ARENA_AMATEUR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PAINT_TRADER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SHUNTER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_JOCK"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_WARRIOR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_T_BONE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_MAYHEM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_WRECKER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_CRASH_COURSE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ARENA_LEGEND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PEGASUS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_CONTACT_SPORT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_UNSTOPPABLE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_LOW_FLOW_CS_DRV_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_LOW_FLOW_CS_TRA_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_LOW_FLOW_CS_FUN_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_LOW_FLOW_CS_PHO_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_LOW_FLOW_CS_FIN_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_LOW_BEN_INTRO_CS_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SCOPEOUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_CREWEDUP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_MOVINGON"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PROMOCAMP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_GUNMAN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SMASHNGRAB"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_INPLAINSI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_UNDETECTED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ALLROUND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ELITETHEIF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PRO"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SUPPORTACT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_SHAFTED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_COLLECTOR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_DEADEYE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PISTOLSATDAWN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_TRAFFICAVOI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_CANTCATCHBRA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_WIZHARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_APEESCAPE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_MONKEYKIND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_AQUAAPE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_KEEPFAITH"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_TRUELOVE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_NEMESIS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_FRIENDZONED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_INTELGATHER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_COMPOUNDINFILT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_LOOT_FINDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_MAX_DISRUPT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_THE_ISLAND_HEIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_GOING_ALONE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_TEAM_WORK"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_MIXING_UP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PRO_THIEF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_CAT_BURGLAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ONE_OF_THEM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_GOLDEN_GUN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ELITE_THIEF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PROFESSIONAL"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_HELPING_OUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_COURIER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PARTY_VIBES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_HELPING_HAND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ELEVENELEVEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_COMPLETE_H4_F_USING_VETIR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_COMPLETE_H4_F_USING_LONGFIN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_COMPLETE_H4_F_USING_ANNIH"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_COMPLETE_H4_F_USING_ALKONOS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_COMPLETE_H4_F_USING_PATROLB"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_FURIA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_MINITANK"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_YOSEMITE2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_ZHABA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_IMORGEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_SULTAN2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_VAGRANT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_VSTR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_STRYDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_SUGOI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_KANJO"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_FORMULA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_FORMULA2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_HELP_JB7002"), TRUE, TRUE);
		}
	}

	static void int_unlocks()
	{
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES0"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES1"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES2"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES3"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES4"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES5"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES6"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES7"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES8"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES9"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES10"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES11"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES12"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES13"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES14"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES15"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES16"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES17"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES18"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES19"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES20"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_HEIST_ACH_TRACKER"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_TOTAL_RACES_WON"), 50, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_TOTAL_RACES_LOST"), 25, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_RACES_WON"), 50, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_RACES_LOST"), 25, TRUE);
		if (g_local_player.character_index == MP0)
		{
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_RACES_WON"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_RACES_LOST"), 25, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_HIGHSCORE_1"), 690, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_HIGHSCORE_2"), 1860, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_HIGHSCORE_3"), 2690, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_HIGHSCORE_4"), 2660, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_HIGHSCORE_5"), 2650, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_HIGHSCORE_6"), 450, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_TARGETS_HIT"), 269, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_WEAPON_BIT_SET"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_YACHT_MISSION_PROG"), 0, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_YACHT_MISSION_FLOW"), 21845, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CASINO_DECORATION_GIFT_1"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_STAM"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_STRN"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_LUNG"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_DRIV"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_FLY"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_SHO"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_STL"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_MECH"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_MOLOTOV_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CMBTPISTOL_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PISTOL50_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_APPISTOL_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_MICROSMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_ASLTSMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_ASLTRIFLE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CRBNRIFLE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_ADVRIFLE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_MG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CMBTMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_ASLTMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PUMP_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SAWNOFF_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_BULLPUP_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_ASLTSHTGN_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SNIPERRFL_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_HVYSNIPER_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_GRNLAUNCH_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_RPG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_MINIGUNS_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_GRENADE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SMKGRENADE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_STKYBMB_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_MOLOTOV_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WIN_LAST_TEAM_STANDINGS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_NIGHTVISION_KILLS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FINISH_HEIST_SETUP_JOB"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FINISH_HEISTS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_KILL_CARRIER_CAPTURE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DROPOFF_CAP_PACKAGES"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WIN_CAPTURES"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NUMBER_SLIPSTREAMS_IN_RACE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_RACES_FASTEST_LAP"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_USJS_COMPLETED"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NUMBER_TURBO_STARTS_IN_RACE"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMWINAIRRACE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMWINSEARACE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMRALLYWONNAV"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMRALLYWONDRIVE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_7_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_6_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_5_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_4_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_3_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_2_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_1_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_9"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_8"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_7"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_6"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_5"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_4"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_3"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_2"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_1"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_0"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ARMOUR_5_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ARMOUR_4_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ARMOUR_3_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ARMOUR_2_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ARMOUR_1_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CIGARETTES_BOUGHT"), 20, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NUMBER_OF_BOURGE_BOUGHT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NUMBER_OF_ORANGE_BOUGHT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NO_BOUGHT_EPIC_SNACKS"), 5, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NO_BOUGHT_HEALTH_SNACKS"), 15, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NO_BOUGHT_YUM_SNACKS"), 30, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_CLUB_DRUNK"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DANCE_TO_BLKMAD"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DANCE_TO_DIXON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DANCE_TO_TALEOFUS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DANCE_TO_SOLOMUN"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_ONLY_PLAYER_ALIVE_LTS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WIN_LAST_TEAM_STANDINGS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_NIGHTVISION_KILLS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FINISH_HEIST_SETUP_JOB"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FINISH_HEISTS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_KILL_CARRIER_CAPTURE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DROPOFF_CAP_PACKAGES"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WIN_CAPTURES"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NUMBER_SLIPSTREAMS_IN_RACE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_RACES_FASTEST_LAP"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_USJS_COMPLETED"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NUMBER_TURBO_STARTS_IN_RACE"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMWINAIRRACE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMWINSEARACE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMRALLYWONNAV"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMRALLYWONDRIVE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_7_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_6_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_5_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_4_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_3_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_2_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_1_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_USJS_FOUND"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_USJS_COMPLETED"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_CONTROL_CROWDS"), 25, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_TRADE_IN_YOUR_PROPERTY"), 25, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_MENTALSTATE_TO_NORMAL"), 25, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_SHOOTRANG_CT_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_SHOOTRANG_RT_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_SHOOTRANG_TG_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_GOLF_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_GOLF_BIRDIES"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_TENNIS_ACE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_TENNIS_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_DM_STOLENKILL"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_DM_3KILLSAMEGUY"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_DM_TOTALKILLS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_DM_KILLSTREAK"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_TDM_MVP"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_TDM_WINS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_DM_WINS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_RACE_LAST_FIRST"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_RACES_FASTEST_LAP"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_GTA_RACES_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_PREPARATION"), 40, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_ASLEEPONJOB"), 20, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DAICASHCRAB"), 100000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_BIGBRO"), 40, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_SHARPSHOOTER"), 40, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_RACECHAMP"), 40, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_BATSWORD"), 1000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_COINPURSE"), 950000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_ASTROCHIMP"), 3000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_MASTERFUL"), 40000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_COINPURSE"), 950000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CH_ARC_CAB_CLAW_TROPHY"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CH_ARC_CAB_LOVE_TROPHY"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H3_COMPLETEDPOSIX"), 0, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CAS_HEIST_FLOW"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H3OPT_ACCESSPOINTS"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H3OPT_POI"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_LOSTANDFOUND"), 500000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_SUNSET"), 1800000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_TREASURE_HUNTER"), 1000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WRECK_DIVING"), 1000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_KEINEMUSIK"), 1800000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_PALMS_TRAX"), 1800000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_MOODYMANN"), 1800000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FILL_YOUR_BAGS"), 10000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WELL_PREPARED"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H4_PLAYTHROUGH_STATUS"), 3, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H4_H4_DJ_MISSIONS"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H4_H4_DJ_MISSIONS_CD"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_ODD_JOBS"), 52, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_VCM_FLOW_PROGRESS"), 1839072, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_VCM_STORY_PROGRESS"), 0, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_GANGOPS_HEIST_STATUS"), 9999, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_LOWRIDER_FLOW_COMPLETE"), 3, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_LOW_FLOW_CURRENT_PROG"), 9, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_LOW_FLOW_CURRENT_CALL"), 9, TRUE);
			// mod sobeit?
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_1_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_2_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_3_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_4_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_5_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_6_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_7_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_VEHICLE_1_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_VEHICLE_2_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_WEAP_ADDON_1_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_WEAP_ADDON_2_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_WEAP_ADDON_3_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_WEAP_ADDON_4_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_WEAP_ADDON_5_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_WEAP_UNLOCKED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_WEAP_UNLOCKED2"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_10_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_11_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_12_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_1_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_2_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_3_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_4_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_5_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_6_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_7_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_8_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_9_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_FM_PURCHASE"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_FM_PURCHASE10"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_FM_PURCHASE11"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_FM_PURCHASE12"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_FM_PURCHASE2"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_FM_PURCHASE3"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_FM_PURCHASE4"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_FM_PURCHASE5"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_FM_PURCHASE6"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_FM_PURCHASE7"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_FM_PURCHASE8"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_KIT_FM_PURCHASE9"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_0"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_1"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_2"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_3"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_4"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_5"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_6"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_7"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_8"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_9"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_10"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_11"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_12"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_13"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_14"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_15"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_16"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_17"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_18"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_19"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_20"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_21"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_22"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_23"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_24"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_25"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_26"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_27"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_28"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_29"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_30"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_31"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_32"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_33"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_34"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_35"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_36"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_37"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_38"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_39"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_40"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_41"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_42"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_43"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_44"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_45"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_46"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_TATTOO_FM_UNLOCKS_47"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_1_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_2_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_3_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_4_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_5_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_6_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_7_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_8_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_9_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_10_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_11_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_1_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_2_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_3_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_4_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_5_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_6_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_7_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_8_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_9_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_10_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CLOTHES_11_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCGW_NUM_WINS_GANG_0"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCGW_NUM_WINS_GANG_1"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCGW_NUM_WINS_GANG_2"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCGW_NUM_WINS_GANG_3"), 50, TRUE);
		}
		else
		{
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_RACES_WON"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_RACES_LOST"), 25, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SR_HIGHSCORE_1"), 690, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SR_HIGHSCORE_2"), 1860, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SR_HIGHSCORE_3"), 2690, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SR_HIGHSCORE_4"), 2660, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SR_HIGHSCORE_5"), 2650, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SR_HIGHSCORE_6"), 450, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SR_TARGETS_HIT"), 269, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SR_WEAPON_BIT_SET"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_YACHT_MISSION_PROG"), 0, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_YACHT_MISSION_FLOW"), 21845, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CASINO_DECORATION_GIFT_1"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_STAM"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_STRN"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_LUNG"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_DRIV"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_FLY"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_SHO"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_STL"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_MECH"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_MOLOTOV_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CMBTPISTOL_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_PISTOL50_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_APPISTOL_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_MICROSMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_ASLTSMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_ASLTRIFLE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CRBNRIFLE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_ADVRIFLE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_MG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CMBTMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_ASLTMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_PUMP_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SAWNOFF_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_BULLPUP_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_ASLTSHTGN_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SNIPERRFL_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_HVYSNIPER_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_GRNLAUNCH_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_RPG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_MINIGUNS_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_GRENADE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SMKGRENADE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_STKYBMB_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_MOLOTOV_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_WIN_LAST_TEAM_STANDINGS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_NIGHTVISION_KILLS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FINISH_HEIST_SETUP_JOB"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FINISH_HEISTS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_KILL_CARRIER_CAPTURE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_DROPOFF_CAP_PACKAGES"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_WIN_CAPTURES"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_NUMBER_SLIPSTREAMS_IN_RACE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_RACES_FASTEST_LAP"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_USJS_COMPLETED"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_NUMBER_TURBO_STARTS_IN_RACE"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FMWINAIRRACE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FMWINSEARACE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FMRALLYWONNAV"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FMRALLYWONDRIVE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_7_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_6_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_5_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_4_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_3_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_2_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_1_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_PILOT_SCHOOL_MEDAL_9"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_PILOT_SCHOOL_MEDAL_8"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_PILOT_SCHOOL_MEDAL_7"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_PILOT_SCHOOL_MEDAL_6"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_PILOT_SCHOOL_MEDAL_5"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_PILOT_SCHOOL_MEDAL_4"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_PILOT_SCHOOL_MEDAL_3"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_PILOT_SCHOOL_MEDAL_2"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_PILOT_SCHOOL_MEDAL_1"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_PILOT_SCHOOL_MEDAL_0"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_ARMOUR_5_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_ARMOUR_4_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_ARMOUR_3_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_ARMOUR_2_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_ARMOUR_1_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CIGARETTES_BOUGHT"), 20, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_NUMBER_OF_BOURGE_BOUGHT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_NUMBER_OF_ORANGE_BOUGHT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_NO_BOUGHT_EPIC_SNACKS"), 5, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_NO_BOUGHT_HEALTH_SNACKS"), 15, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_NO_BOUGHT_YUM_SNACKS"), 30, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_CLUB_DRUNK"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_DANCE_TO_BLKMAD"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_DANCE_TO_DIXON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_DANCE_TO_TALEOFUS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_DANCE_TO_SOLOMUN"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_ONLY_PLAYER_ALIVE_LTS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_WIN_LAST_TEAM_STANDINGS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_NIGHTVISION_KILLS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FINISH_HEIST_SETUP_JOB"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FINISH_HEISTS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_KILL_CARRIER_CAPTURE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_DROPOFF_CAP_PACKAGES"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_WIN_CAPTURES"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_NUMBER_SLIPSTREAMS_IN_RACE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_RACES_FASTEST_LAP"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_USJS_COMPLETED"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_NUMBER_TURBO_STARTS_IN_RACE"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FMWINAIRRACE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FMWINSEARACE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FMRALLYWONNAV"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FMRALLYWONDRIVE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_7_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_6_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_5_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_4_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_3_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_2_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_1_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_USJS_FOUND"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_USJS_COMPLETED"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_CONTROL_CROWDS"), 25, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_TRADE_IN_YOUR_PROPERTY"), 25, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_MENTALSTATE_TO_NORMAL"), 25, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_SHOOTRANG_CT_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_SHOOTRANG_RT_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_SHOOTRANG_TG_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_GOLF_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_GOLF_BIRDIES"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_TENNIS_ACE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_TENNIS_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_DM_STOLENKILL"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_DM_3KILLSAMEGUY"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_DM_TOTALKILLS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_DM_KILLSTREAK"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_TDM_MVP"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_TDM_WINS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_DM_WINS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_RACE_LAST_FIRST"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_RACES_FASTEST_LAP"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FM_GTA_RACES_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_PREPARATION"), 40, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_ASLEEPONJOB"), 20, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_DAICASHCRAB"), 100000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_BIGBRO"), 40, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_SHARPSHOOTER"), 40, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_RACECHAMP"), 40, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_BATSWORD"), 1000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_COINPURSE"), 950000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_ASTROCHIMP"), 3000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_MASTERFUL"), 40000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_COINPURSE"), 950000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CH_ARC_CAB_CLAW_TROPHY"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CH_ARC_CAB_LOVE_TROPHY"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_H3_COMPLETEDPOSIX"), 0, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CAS_HEIST_FLOW"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_H3OPT_ACCESSPOINTS"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_H3OPT_POI"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_LOSTANDFOUND"), 500000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_SUNSET"), 1800000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_TREASURE_HUNTER"), 1000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_WRECK_DIVING"), 1000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_KEINEMUSIK"), 1800000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_PALMS_TRAX"), 1800000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_MOODYMANN"), 1800000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FILL_YOUR_BAGS"), 10000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_WELL_PREPARED"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_H4_PLAYTHROUGH_STATUS"), 3, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_H4_H4_DJ_MISSIONS"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_H4_H4_DJ_MISSIONS_CD"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_ODD_JOBS"), 52, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_VCM_FLOW_PROGRESS"), 1839072, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_VCM_STORY_PROGRESS"), 0, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_LOWRIDER_FLOW_COMPLETE"), 3, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_LOW_FLOW_CURRENT_PROG"), 9, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_LOW_FLOW_CURRENT_CALL"), 9, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_1_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_2_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_3_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_4_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_5_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_6_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CARMOD_7_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_VEHICLE_1_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_VEHICLE_2_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_WEAP_ADDON_1_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_WEAP_ADDON_2_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_WEAP_ADDON_3_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_WEAP_ADDON_4_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_WEAP_ADDON_5_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_WEAP_UNLOCKED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_WEAP_UNLOCKED2"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_10_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_11_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_12_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_1_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_2_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_3_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_4_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_5_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_6_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_7_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_8_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_9_FM_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_FM_PURCHASE"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_FM_PURCHASE10"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_FM_PURCHASE11"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_FM_PURCHASE12"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_FM_PURCHASE2"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_FM_PURCHASE3"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_FM_PURCHASE4"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_FM_PURCHASE5"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_FM_PURCHASE6"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_FM_PURCHASE7"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_FM_PURCHASE8"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_KIT_FM_PURCHASE9"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_0"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_1"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_2"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_3"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_4"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_5"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_6"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_7"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_8"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_9"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_10"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_11"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_12"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_13"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_14"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_15"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_16"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_17"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_18"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_19"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_20"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_21"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_22"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_23"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_24"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_25"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_26"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_27"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_28"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_29"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_30"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_31"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_32"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_33"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_34"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_35"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_36"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_37"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_38"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_39"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_40"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_41"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_42"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_43"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_44"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_TATTOO_FM_UNLOCKS_45"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_1_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_2_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_3_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_4_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_5_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_6_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_7_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_8_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_9_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_10_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_11_UNLCK"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_1_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_2_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_3_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_4_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_5_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_6_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_7_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_8_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_9_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_10_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_CLOTHES_11_OWNED"), 0xFFFFFFFF, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCGW_NUM_WINS_GANG_0"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCGW_NUM_WINS_GANG_1"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCGW_NUM_WINS_GANG_2"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCGW_NUM_WINS_GANG_3"), 50, TRUE);
		}
	}
}