#include "common.hpp"
#include "imgui.h"
#include "script.hpp"
#include "fiber_pool.hpp"
#include "natives.hpp"
#include "gta_util.hpp"
#include <features.hpp>
#include <gui.hpp>
#include <script_local.hpp>
#include "stat_editor.h"
#include "base_tab.h"
#include <script_global.hpp>
#include <gta/VehicleValues.h>
#include <misc/cpp/imgui_stdlib.h>
#include <local_player.hpp>
#include <imgui.cpp>
#include "diamond_casino_heist.h"

using namespace big;

namespace big
{
	static void set_packed_bool(bool value, const char* section, int32_t min_i, int32_t max_i)
	{
		for (auto index = min_i; index <= max_i; index++)
		{
			auto hash = STATS::_GET_NGSTAT_BOOL_HASH((index - min_i), FALSE, TRUE, g_local_player.character_index, section);
			auto mask = ((index - min_i) - STATS::_0xF4D8E7AC2A27758C((index - min_i)) * 64);
			STATS::STAT_SET_BOOL_MASKED(hash, value, mask, TRUE);
		}
	}

	// example: set_packed_bool(31736, true, "_TUNERPSTAT_BOOL", 31707)
	/*
	HUD::CLEAR_HELP(true);
	func_799("BURIED_OUTHEL2", -1);
	HUD::BEGIN_TEXT_COMMAND_THEFEED_POST("BURIED_OUTTIC");
	HUD::END_TEXT_COMMAND_THEFEED_POST_UNLOCK_TU("CLOTHES_UNLOCK", 7, "BURIED_OUTHEL", 1);
	func_19945(31736, 1, -1, 1);
	*/
	static void set_unique_packed_bool(int32_t index, bool value, const char* section, int32_t index_f)
	{
		auto hash = STATS::_GET_NGSTAT_BOOL_HASH((index - index_f), FALSE, TRUE, g_local_player.character_index, section);
		auto mask = ((index - index_f) - STATS::_0xF4D8E7AC2A27758C((index - index_f)) * 64);
		STATS::STAT_SET_BOOL_MASKED(hash, value, mask, TRUE);
	}

	static void unlock_everything_bool()
	{
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_MELEECHLENGECOMPLETED"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_HEADSHOTCHLENGECOMPLETED"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_COMPLET_HEIST_MEM"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_COMPLET_HEIST_1STPER"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_FLEECA_FIN"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_HST_ORDER"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_HST_SAME_TEAM"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_HST_ULT_CHAL"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_HUMANE_FIN"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_PACIFIC_FIN"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_PRISON_FIN"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_SERIESA_FIN"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_IAA"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_SUBMARINE"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_MISSILE"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_SUPPORT"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_LOYALTY2"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_LOYALTY3"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_CRIMMASMD2"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_CRIMMASMD3"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_ALLINORDER"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_LOYALTY"), TRUE, TRUE);
		STATS::STAT_SET_BOOL(RAGE_JOAAT("MPPLY_AWD_GANGOPS_CRIMMASMD"), TRUE, TRUE);
		if (g_local_player.character_index == MP0)
		{
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_INTELGATHER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COMPOUNDINFILT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_LOOT_FINDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MAX_DISRUPT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_THE_ISLAND_HEIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GOING_ALONE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TEAM_WORK"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MIXING_UP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PRO_THIEF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CAT_BURGLAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ONE_OF_THEM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GOLDEN_GUN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELITE_THIEF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PROFESSIONAL"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_HELPING_OUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COURIER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PARTY_VIBES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_HELPING_HAND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELEVENELEVEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_VCM_FLOW_CS_RSC_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_VCM_FLOW_CS_BWL_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_VCM_FLOW_CS_MTG_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_VCM_FLOW_CS_OIL_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_VCM_FLOW_CS_DEF_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_VCM_FLOW_CS_FIN_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CAS_VEHICLE_REWARD"), FALSE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_WAS_CHAR_TRANSFERED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_RACE_MODDED_CAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_DRIVE_RALLY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_GTA_RACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_BOAT_RACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_FOOT_RACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_TEAM_DM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_VEHICLE_DM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_MISSION_CONTACT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_A_PLAYLIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_POINT_TO_POINT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_ONE_ON_ONE_DM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PLAY_ONE_ON_ONE_RACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_SURV_A_BOUNTY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_SET_WANTED_LVL_ON_PLAY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_GANG_BACKUP_GANGS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_GANG_BACKUP_LOST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_GANG_BACKUP_VAGOS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_CALL_MERCENARIES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_PHONE_MECH_DROP_CAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_GONE_OFF_RADAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_FILL_TITAN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_MOD_CAR_USING_APP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_BUY_APPARTMENT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_BUY_INSURANCE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_BUY_GARAGE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_ENTER_FRIENDS_HOUSE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_CALL_STRIPPER_HOUSE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_CALL_FRIEND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_SEND_FRIEND_REQUEST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CL_W_WANTED_PLAYER_TV"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_0"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_1"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_3"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_4"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_5"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_6"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_7"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_8"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_PILOT_ASPASSEDLESSON_9"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIRST_TIME1"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIRST_TIME2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIRST_TIME3"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIRST_TIME4"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIRST_TIME5"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIRST_TIME6"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ALL_IN_ORDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SUPPORTING_ROLE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ACTIVATE_2_PERSON_KEY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ALL_ROLES_HEIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_LEADER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SURVIVALIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SCOPEOUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CREWEDUP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MOVINGON"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PROMOCAMP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GUNMAN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SMASHNGRAB"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_INPLAINSI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_UNDETECTED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ALLROUND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELITETHEIF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PRO"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SUPPORTACT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SHAFTED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COLLECTOR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_DEADEYE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PISTOLSATDAWN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TRAFFICAVOI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CANTCATCHBRA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_WIZHARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_APEESCAPE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MONKEYKIND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_AQUAAPE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_KEEPFAITH"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TRUELOVE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_NEMESIS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FRIENDZONED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_BUY_EVERY_GUN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_DAILYOBJMONTHBONUS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_DAILYOBJWEEKBONUS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_DRIVELESTERCAR5MINS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FINISH_HEIST_NO_DAMAGE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM25DIFFERENTDM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM25DIFFERENTRACES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM25DIFITEMSCLOTHES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMFURTHESTWHEELIE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM6DARTCHKOUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM_GOLF_HOLE_IN_1"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM_SHOOTRANG_GRAN_WON"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FM_TENNIS_5_SET_WINS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMATTGANGHQ"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMFULLYMODDEDCAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMKILL3ANDWINGTARACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMKILLSTREAKSDM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMMOSTKILLSGANGHIDE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMMOSTKILLSSURVIVE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMPICKUPDLCCRATE1ST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMRACEWORLDRECHOLDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMTATTOOALLBODYPARTS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMWINALLRACEMODES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMWINCUSTOMRACE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FMWINEVERYGAMEMODE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SPLIT_HEIST_TAKE_EVENLY"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_STORE_20_CAR_IN_GARAGES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_SR_TIER_1_REWARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_SR_TIER_3_REWARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_SR_INCREASE_THROW_CAP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CLUB_COORD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CLUB_HOTSPOT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CLUB_CLUBBER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_BEGINNER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FIELD_FILLER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ARMCHAIR_RACER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_LEARNER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SUNDAY_DRIVER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_THE_ROOKIE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_BUMP_AND_RUN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GEAR_HEAD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_DOOR_SLAMMER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_HOT_LAP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ARENA_AMATEUR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PAINT_TRADER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SHUNTER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_JOCK"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_WARRIOR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_T_BONE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MAYHEM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_WRECKER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CRASH_COURSE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ARENA_LEGEND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PEGASUS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CONTACT_SPORT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_UNSTOPPABLE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_LOW_FLOW_CS_DRV_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_LOW_FLOW_CS_TRA_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_LOW_FLOW_CS_FUN_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_LOW_FLOW_CS_PHO_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_LOW_FLOW_CS_FIN_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_LOW_BEN_INTRO_CS_SEEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SCOPEOUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CREWEDUP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MOVINGON"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PROMOCAMP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GUNMAN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SMASHNGRAB"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_INPLAINSI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_UNDETECTED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ALLROUND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELITETHEIF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PRO"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SUPPORTACT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_SHAFTED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COLLECTOR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_DEADEYE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PISTOLSATDAWN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TRAFFICAVOI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CANTCATCHBRA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_WIZHARD"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_APEESCAPE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MONKEYKIND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_AQUAAPE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_KEEPFAITH"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TRUELOVE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_NEMESIS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_FRIENDZONED"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_INTELGATHER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COMPOUNDINFILT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_LOOT_FINDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MAX_DISRUPT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_THE_ISLAND_HEIST"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GOING_ALONE"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TEAM_WORK"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MIXING_UP"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PRO_THIEF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CAT_BURGLAR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ONE_OF_THEM"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GOLDEN_GUN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELITE_THIEF"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PROFESSIONAL"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_HELPING_OUT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COURIER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PARTY_VIBES"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_HELPING_HAND"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELEVENELEVEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_COMPLETE_H4_F_USING_VETIR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_COMPLETE_H4_F_USING_LONGFIN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_COMPLETE_H4_F_USING_ANNIH"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_COMPLETE_H4_F_USING_ALKONOS"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_COMPLETE_H4_F_USING_PATROLB"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_FURIA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_MINITANK"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_YOSEMITE2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_ZHABA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_IMORGEN"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_SULTAN2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_VAGRANT"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_VSTR"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_STRYDER"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_SUGOI"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_KANJO"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_FORMULA"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_FORMULA2"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_HELP_JB7002"), TRUE, TRUE);
			STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_CHAR_TRANSFERED"), TRUE, TRUE);
		}
	}

	static void unlock_everything_int()
	{
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES0"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES1"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES2"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES3"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES4"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES5"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES6"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES7"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES8"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES9"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES10"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES11"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES12"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES13"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES14"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES15"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_XMASLIVERIES16"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_HEIST_ACH_TRACKER"), -1, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_TOTAL_RACES_WON"), 50, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_TOTAL_RACES_LOST"), 25, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_RACES_WON"), 50, TRUE);
		STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_RACES_LOST"), 25, TRUE);
		if (g_local_player.character_index == MP0)
		{
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_RACES_WON"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_RACES_LOST"), 25, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_HIGHSCORE_1"), 690, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_HIGHSCORE_2"), 1860, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_HIGHSCORE_3"), 2690, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_HIGHSCORE_4"), 2660, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_HIGHSCORE_5"), 2650, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_HIGHSCORE_6"), 450, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_TARGETS_HIT"), 269, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SR_WEAPON_BIT_SET"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_YACHT_MISSION_PROG"), 0, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_YACHT_MISSION_FLOW"), 21845, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CASINO_DECORATION_GIFT_1"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_STAM"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_STRN"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_LUNG"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_DRIV"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_FLY"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_SHO"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_STL"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_MECH"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_MOLOTOV_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CMBTPISTOL_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PISTOL50_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_APPISTOL_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_MICROSMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_ASLTSMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_ASLTRIFLE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CRBNRIFLE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_ADVRIFLE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_MG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CMBTMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_ASLTMG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PUMP_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SAWNOFF_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_BULLPUP_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_ASLTSHTGN_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SNIPERRFL_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_HVYSNIPER_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_GRNLAUNCH_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_RPG_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_MINIGUNS_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_GRENADE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SMKGRENADE_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_STKYBMB_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_MOLOTOV_ENEMY_KILLS"), 600, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WIN_LAST_TEAM_STANDINGS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_NIGHTVISION_KILLS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FINISH_HEIST_SETUP_JOB"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FINISH_HEISTS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_KILL_CARRIER_CAPTURE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DROPOFF_CAP_PACKAGES"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WIN_CAPTURES"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NUMBER_SLIPSTREAMS_IN_RACE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_RACES_FASTEST_LAP"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_USJS_COMPLETED"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NUMBER_TURBO_STARTS_IN_RACE"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMWINAIRRACE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMWINSEARACE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMRALLYWONNAV"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMRALLYWONDRIVE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_7_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_6_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_5_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_4_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_3_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_2_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_1_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_9"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_8"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_7"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_6"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_5"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_4"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_3"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_2"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_1"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_PILOT_SCHOOL_MEDAL_0"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ARMOUR_5_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ARMOUR_4_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ARMOUR_3_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ARMOUR_2_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ARMOUR_1_COUNT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CIGARETTES_BOUGHT"), 20, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NUMBER_OF_BOURGE_BOUGHT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NUMBER_OF_ORANGE_BOUGHT"), 10, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NO_BOUGHT_EPIC_SNACKS"), 5, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NO_BOUGHT_HEALTH_SNACKS"), 15, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NO_BOUGHT_YUM_SNACKS"), 30, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_CLUB_DRUNK"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DANCE_TO_BLKMAD"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DANCE_TO_DIXON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DANCE_TO_TALEOFUS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DANCE_TO_SOLOMUN"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_ONLY_PLAYER_ALIVE_LTS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WIN_LAST_TEAM_STANDINGS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_NIGHTVISION_KILLS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FINISH_HEIST_SETUP_JOB"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FINISH_HEISTS"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_KILL_CARRIER_CAPTURE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DROPOFF_CAP_PACKAGES"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WIN_CAPTURES"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NUMBER_SLIPSTREAMS_IN_RACE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_RACES_FASTEST_LAP"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_USJS_COMPLETED"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_NUMBER_TURBO_STARTS_IN_RACE"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMWINAIRRACE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMWINSEARACE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMRALLYWONNAV"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FMRALLYWONDRIVE"), 1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_7_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_6_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_5_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_4_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_3_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_2_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_CARMOD_1_UNLCK"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_USJS_FOUND"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_USJS_COMPLETED"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_CONTROL_CROWDS"), 25, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_TRADE_IN_YOUR_PROPERTY"), 25, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_MENTALSTATE_TO_NORMAL"), 25, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_SHOOTRANG_CT_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_SHOOTRANG_RT_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_SHOOTRANG_TG_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_GOLF_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_GOLF_BIRDIES"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_TENNIS_ACE"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_TENNIS_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_DM_STOLENKILL"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_DM_3KILLSAMEGUY"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_DM_TOTALKILLS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_DM_KILLSTREAK"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_TDM_MVP"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_TDM_WINS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_DM_WINS"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_RACE_LAST_FIRST"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_RACES_FASTEST_LAP"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FM_GTA_RACES_WON"), 100, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_PREPARATION"), 40, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_ASLEEPONJOB"), 20, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_DAICASHCRAB"), 100000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_BIGBRO"), 40, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_SHARPSHOOTER"), 40, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_RACECHAMP"), 40, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_BATSWORD"), 1000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_COINPURSE"), 950000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_ASTROCHIMP"), 3000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_MASTERFUL"), 40000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_COINPURSE"), 950000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CH_ARC_CAB_CLAW_TROPHY"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CH_ARC_CAB_LOVE_TROPHY"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H3_COMPLETEDPOSIX"), 0, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CAS_HEIST_FLOW"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H3OPT_ACCESSPOINTS"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H3OPT_POI"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_LOSTANDFOUND"), 500000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_SUNSET"), 1800000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_TREASURE_HUNTER"), 1000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WRECK_DIVING"), 1000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_KEINEMUSIK"), 1800000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_PALMS_TRAX"), 1800000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_MOODYMANN"), 1800000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FILL_YOUR_BAGS"), 10000000, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WELL_PREPARED"), 50, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H4_PLAYTHROUGH_STATUS"), 3, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H4_H4_DJ_MISSIONS"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H4_H4_DJ_MISSIONS_CD"), -1, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_ODD_JOBS"), 52, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_VCM_FLOW_PROGRESS"), 1839072, TRUE);
			STATS::STAT_SET_INT(RAGE_JOAAT("MP0_VCM_STORY_PROGRESS"), 0, TRUE);
		}
	}

	int get_rp_value(int value)
	{
		return *script_global(293361).at(value + 1).as<int*>();
	}

	void base_tab::render_base_tab()
	{
		if (ImGui::BeginTabItem("Online"))
		{
			ImGui::Text("Ballistic Equipment");
			static int ballisticarmorvalue;
			ImGui::InputInt("###ballisticarmorvalue", &ballisticarmorvalue);
			ImGui::SameLine();
			if (ImGui::Button("Set Ballistic Armor Value"))
			{
				g_fiber_pool->queue_job([]
					{
						*script_global(262145).at(19995).as<int*>() = ballisticarmorvalue;
					});
			}
			ImGui::Separator();
			ImGui::Text("Helpful shit");
			if (ImGui::Button("Clear Wanted Level"))
			{
				QUEUE_JOB_BEGIN_CLAUSE()
				{
					if (auto player_info = gta_util::get_local_playerinfo())
						if (player_info->m_is_wanted)
							player_info->m_wanted_level = 0;
				} QUEUE_JOB_END_CLAUSE
			}
			ImGui::SameLine();
			if (ImGui::Button("Stop Cutscene")) 
			{ 
				QUEUE_JOB_BEGIN_CLAUSE() 
				{ 
					CUTSCENE::STOP_CUTSCENE_IMMEDIATELY(); 
				} QUEUE_JOB_END_CLAUSE 
			}
			ImGui::SameLine();
			if (ImGui::Button("Go Into Personal Vehicle"))
			{
				QUEUE_JOB_BEGIN_CLAUSE()
				{
					// Global_2409299.f_8 = 0;
					*script_global(2409299).at(8).as<int*>() = 1;
				} QUEUE_JOB_END_CLAUSE
			}
			ImGui::Separator();
			ImGui::Text("Level");
			static int level{};
			ImGui::PushItemWidth(200);
			ImGui::InputInt("Level", &level);
			ImGui::PopItemWidth();
			ImGui::SameLine();
			if (ImGui::Button("Apply"))
			{
				QUEUE_JOB_BEGIN_CLAUSE()
				{
					if (level > 0 && level < 8000)
					{
						STATS::STAT_SET_INT(RAGE_JOAAT("MPPLY_GLOBALXP"), get_rp_value(level), true);
						if (g_local_player.character_index == 0)
						{
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_XP_FM"), get_rp_value(level), TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_SET_RP_GIFT_ADMIN"), get_rp_value(level), TRUE);
						}
						else
						{
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_XP_FM"), get_rp_value(level), TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_SET_RP_GIFT_ADMIN"), get_rp_value(level), TRUE);
						}
					}
				} QUEUE_JOB_END_CLAUSE
			}

			ImGui::Separator();
			ImGui::Text("Packed Bools");
			static int packed_bool{};
			const char* const packed_bools[]{ "_NGPSTAT_BOOL", "_NGTATPSTAT_BOOL", "_NGDLCPSTAT_BOOL", "_DLCBIKEPSTAT_BOOL", "_DLCGUNPSTAT_BOOL", "_GUNTATPSTAT_BOOL", "_DLCSMUGCHARPSTAT_BOOL", "_GANGOPSPSTAT_BOOL", "_BUSINESSBATPSTAT_BOOL", "_ARENAWARSPSTAT_BOOL", "_CASINOPSTAT_BOOL", "_CASINOHSTPSTAT_BOOL", "_HEIST3TATTOOSTAT_BOOL", "_SU20PSTAT_BOOL", "_SU20TATTOOSTAT_BOOL", "_HISLANDPSTAT_BOOL", "_TUNERPSTAT_BOOL" };
			ImGui::PushItemWidth(300.f);
			ImGui::Combo("Packed Bools", &packed_bool, packed_bools, (int)(sizeof(packed_bools) / sizeof(*packed_bools)));
			ImGui::PopItemWidth();
			ImGui::SameLine();
			if (ImGui::Button("Apply Packed Bool"))
			{
				switch (packed_bool)
				{
				case 0:
				{
					set_packed_bool(true, "_NGPSTAT_BOOL", 4207, 4399);
					break;
				}
				case 1:
				{
					set_packed_bool(true, "_NGTATPSTAT_BOOL", 6029, 6413);
					break;
				}
				case 2:
				{
					set_packed_bool(true, "_NGDLCPSTAT_BOOL", 7385, 7641);
					break;
				}
				case 3:
				{
					set_packed_bool(true, "_DLCBIKEPSTAT_BOOL", 9361, 9553);
					break;
				}
				case 4:
				{
					set_packed_bool(true, "_DLCGUNPSTAT_BOOL", 15369, 15561);
					break;
				}
				case 5:
				{
					set_packed_bool(true, "_GUNTATPSTAT_BOOL", 15562, 15946);
					break;
				}
				case 6:
				{
					set_packed_bool(true, "_DLCSMUGCHARPSTAT_BOOL", 15946, 16010);
					break;
				}
				case 7:
				{
					set_packed_bool(true, "_GANGOPSPSTAT_BOOL", 18098, 18162);
					break;
				}
				case 8:
				{
					set_packed_bool(true, "_BUSINESSBATPSTAT_BOOL", 22066, 22194);
					break;
				}
				case 9:
				{
					set_packed_bool(true, "_ARENAWARSPSTAT_BOOL", 24962, 25538);
					break;
				}
				case 10:
				{
					set_packed_bool(true, "_CASINOPSTAT_BOOL", 26810, 27258);
					break;
				}
				case 11:
				{
					set_packed_bool(true, "_CASINOHSTPSTAT_BOOL", 28098, 28354);
					break;
				}
				case 12:
				{

					set_packed_bool(true, "_HEIST3TATTOOSTAT_BOOL", 28355, 28483);
					break;
				}
				case 13:
				{
					set_packed_bool(true, "_SU20PSTAT_BOOL", 30227, 30355);
					break;
				}
				case 14:
				{

					set_packed_bool(true, "_SU20TATTOOSTAT_BOOL", 30355, 30483);
					break;
				}
				case 15:
				{
					set_packed_bool(true, "_HISLANDPSTAT_BOOL", 30515, 30707);
					break;
				}
				case 16:
				{
					set_packed_bool(true, "_TUNERPSTAT_BOOL", 31707, 32283);
					break;
				}
				}
			}
			ImGui::SameLine();
			if (ImGui::Button("Revert Packed Bool"))
			{
				switch (packed_bool)
				{
				case 0:
				{
					set_packed_bool(false, "_NGPSTAT_BOOL", 4207, 4399);
					break;
				}
				case 1:
				{
					set_packed_bool(false, "_NGTATPSTAT_BOOL", 6029, 6413);
					break;
				}
				case 2:
				{
					set_packed_bool(false, "_NGDLCPSTAT_BOOL", 7385, 7641);
					break;
				}
				case 3:
				{
					set_packed_bool(false, "_DLCBIKEPSTAT_BOOL", 9361, 9553);
					break;
				}
				case 4:
				{
					set_packed_bool(false, "_DLCGUNPSTAT_BOOL", 15369, 15561);
					break;
				}
				case 5:
				{
					set_packed_bool(false, "_GUNTATPSTAT_BOOL", 15562, 15946);
					break;
				}
				case 6:
				{
					set_packed_bool(false, "_DLCSMUGCHARPSTAT_BOOL", 15946, 16010);
					break;
				}
				case 7:
				{
					set_packed_bool(false, "_GANGOPSPSTAT_BOOL", 18098, 18162);
					break;
				}
				case 8:
				{
					set_packed_bool(false, "_BUSINESSBATPSTAT_BOOL", 22066, 22194);
					break;
				}
				case 9:
				{
					set_packed_bool(false, "_ARENAWARSPSTAT_BOOL", 24962, 25538);
					break;
				}
				case 10:
				{
					set_packed_bool(false, "_CASINOPSTAT_BOOL", 26810, 27258);
					break;
				}
				case 11:
				{
					set_packed_bool(false, "_CASINOHSTPSTAT_BOOL", 28098, 28354);
					break;
				}
				case 12:
				{

					set_packed_bool(false, "_HEIST3TATTOOSTAT_BOOL", 28355, 28483);
					break;
				}
				case 13:
				{
					set_packed_bool(false, "_SU20PSTAT_BOOL", 30227, 30355);
					break;
				}
				case 14:
				{

					set_packed_bool(false, "_SU20TATTOOSTAT_BOOL", 30355, 30483);
					break;
				}
				case 15:
				{
					set_packed_bool(false, "_HISLANDPSTAT_BOOL", 30515, 30707);
					break;
				}
				case 16:
				{
					set_packed_bool(false, "_TUNERPSTAT_BOOL", 31707, 32283);
					break;
				}
				}
			}

			ImGui::Text("_SU20PSTAT_BOOL -> Summer Update.\n_CASINOPSTAT_BOOL -> Casino DLC.\n_CASINOHSTPSTAT_BOOL -> Casino Heist DLC (arcade stuff etc.).\n_DLCGUNPSTAT_BOOL -> Gun Running DLC (bunker research).\n_ARENAWARSPSTAT_BOOL -> Arena Wars DLC.\n_HISLANDPSTAT_BOOL -> Cayo Perico Heist DLC (golden gun etc.).\n_DLCBIKEPSTAT_BOOL -> Bikers DLC.\n_TUNERPSTAT_BOOL -> Tuners DLC");

			ImGui::Separator();
			ImGui::Text("Unlocks");
			if (ImGui::Button("Reset Mental State"))
			{
				QUEUE_JOB_BEGIN_CLAUSE()
				{
					STATS::STAT_SET_FLOAT(RAGE_JOAAT("MPPLY_PLAYER_MENTAL_STATE"), 0.f, true);
					if (g_local_player.character_index == MP0)
					{
						STATS::STAT_SET_FLOAT(RAGE_JOAAT("MP0_PLAYER_MENTAL_STATE"), 0.f, true);
					}
					else
					{
						STATS::STAT_SET_FLOAT(RAGE_JOAAT("MP1_PLAYER_MENTAL_STATE"), 0.f, true);
					}
				} QUEUE_JOB_END_CLAUSE
			}

			static int unlock{};
			const char* const unlocks[]{ "Bools", "Ints", "Stats", "Modded Run", "Shotaro", "Cayo Perico Heist", "Diamond Casino Heist", "Bunker Research" };
			ImGui::PushItemWidth(185.f);
			ImGui::Combo("Unlocks", &unlock, unlocks, (int)(sizeof(unlocks) / sizeof(*unlocks)));
			ImGui::SameLine();
			if (ImGui::Button("Unlock"))
			{
				switch (unlock)
				{
				case 0:
				{
					QUEUE_JOB_BEGIN_CLAUSE()
					{
						unlock_everything_bool();
					} QUEUE_JOB_END_CLAUSE
						break;
				}
				case 1:
				{
					QUEUE_JOB_BEGIN_CLAUSE()
					{
						unlock_everything_int();
					} QUEUE_JOB_END_CLAUSE
						break;
				}
				case 2:
				{
					QUEUE_JOB_BEGIN_CLAUSE()
					{
						if (g_local_player.character_index == MP0)
						{
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_STAM"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_STRN"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_FLY"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_STL"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_LUNG"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_DRIV"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_SCRIPT_INCREASE_SHO"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_HEALTH_1_UNLCK"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_HEALTH_2_UNLCK"), -1, TRUE);
						}
						else
						{
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_STAM"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_STRN"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_FLY"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_STL"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_LUNG"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_DRIV"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_SCRIPT_INCREASE_SHO"), 100, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_HEALTH_1_UNLCK"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_HEALTH_2_UNLCK"), -1, TRUE);
						}
					} QUEUE_JOB_END_CLAUSE
						break;
				}
				case 3:
				{
					QUEUE_JOB_BEGIN_CLAUSE()
					{
						if (g_local_player.character_index == MP0)
						{
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ABILITY_1_UNLCK"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ABILITY_2_UNLCK"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_ABILITY_3_UNLCK"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_ABILITY_1_UNLCK"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_ABILITY_2_UNLCK"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CHAR_FM_ABILITY_3_UNLCK"), -1, TRUE);
						}
						else
						{
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_ABILITY_1_UNLCK"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_ABILITY_2_UNLCK"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_ABILITY_3_UNLCK"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_ABILITY_1_UNLCK"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_ABILITY_2_UNLCK"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CHAR_FM_ABILITY_3_UNLCK"), -1, TRUE);
						}
					} QUEUE_JOB_END_CLAUSE
						break;
				}
				case 4:
				{
					QUEUE_JOB_BEGIN_CLAUSE()
					{
						if (g_local_player.character_index == MP0)
						{
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CRDEADLINE"), 5, TRUE);
						}
						else
						{
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CRDEADLINE"), 5, TRUE);
						}
					} QUEUE_JOB_END_CLAUSE
						break;
				}
				case 5:
				{
					QUEUE_JOB_BEGIN_CLAUSE()
					{
						if (g_local_player.character_index == MP0)
						{
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_LOSTANDFOUND"), 500000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_SUNSET"), 1800000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_TREASURE_HUNTER"), 1000000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WRECK_DIVING"), 1000000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_KEINEMUSIK"), 1800000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_PALMS_TRAX"), 1800000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_MOODYMANN"), 1800000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_FILL_YOUR_BAGS"), 10000000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_AWD_WELL_PREPARED"), 50, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H4_PLAYTHROUGH_STATUS"), 3, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_INTELGATHER"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COMPOUNDINFILT"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_LOOT_FINDER"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MAX_DISRUPT"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_THE_ISLAND_HEIST"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GOING_ALONE"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_TEAM_WORK"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_MIXING_UP"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PRO_THIEF"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_CAT_BURGLAR"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ONE_OF_THEM"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_GOLDEN_GUN"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELITE_THIEF"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PROFESSIONAL"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_HELPING_OUT"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_COURIER"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_PARTY_VIBES"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_HELPING_HAND"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP0_AWD_ELEVENELEVEN"), TRUE, TRUE);
						}
						else
						{
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_LOSTANDFOUND"), 500000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_SUNSET"), 1800000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_TREASURE_HUNTER"), 1000000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_WRECK_DIVING"), 1000000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_KEINEMUSIK"), 1800000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_PALMS_TRAX"), 1800000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_MOODYMANN"), 1800000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_FILL_YOUR_BAGS"), 10000000, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_AWD_WELL_PREPARED"), 50, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_H4_PLAYTHROUGH_STATUS"), 3, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_INTELGATHER"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_COMPOUNDINFILT"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_LOOT_FINDER"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_MAX_DISRUPT"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_THE_ISLAND_HEIST"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_GOING_ALONE"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_TEAM_WORK"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_MIXING_UP"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PRO_THIEF"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_CAT_BURGLAR"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ONE_OF_THEM"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_GOLDEN_GUN"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ELITE_THIEF"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PROFESSIONAL"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_HELPING_OUT"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_COURIER"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_PARTY_VIBES"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_HELPING_HAND"), TRUE, TRUE);
							STATS::STAT_SET_BOOL(RAGE_JOAAT("MP1_AWD_ELEVENELEVEN"), TRUE, TRUE);
						}
					} QUEUE_JOB_END_CLAUSE
						break;
				}
				case 6:
				{
					QUEUE_JOB_BEGIN_CLAUSE()
					{
						if (g_local_player.character_index == MP0)
						{
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H3_COMPLETEDPOSIX"), 0, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_CAS_HEIST_FLOW"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H3OPT_ACCESSPOINTS"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP0_H3OPT_POI"), -1, TRUE);
						}
						else
						{
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_H3_COMPLETEDPOSIX"), 0, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_CAS_HEIST_FLOW"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_H3OPT_ACCESSPOINTS"), -1, TRUE);
							STATS::STAT_SET_INT(RAGE_JOAAT("MP1_H3OPT_POI"), -1, TRUE);
						}
					} QUEUE_JOB_END_CLAUSE
						break;
				}
				case 7:
				{
					QUEUE_JOB_BEGIN_CLAUSE()
					{
						set_unique_packed_bool(15381, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15382, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15428, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15429, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15430, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15431, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15491, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15432, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15433, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15434, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15435, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15436, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15437, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15438, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15439, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15447, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15448, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15449, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15450, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15451, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15452, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15453, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15454, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15455, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15456, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15457, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15458, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15459, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15460, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15461, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15462, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15463, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15464, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15465, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15466, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15467, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15468, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15469, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15470, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15471, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15472, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15473, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15474, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15492, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15493, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15494, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15495, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15496, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15497, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15498, true, "_DLCGUNPSTAT_BOOL", 15369);
						set_unique_packed_bool(15499, true, "_DLCGUNPSTAT_BOOL", 15369);
					} QUEUE_JOB_END_CLAUSE
						break;
				}
				}
			}
			ImGui::PopItemWidth();

			if (ImGui::CollapsingHeader("Diamond Casino Heist"))
			{
				diamond_casino_heist::do_presentation_layer();
			}
			ImGui::EndTabItem();
		}

		stat_editor::render();

		if (ImGui::BeginTabItem("Settings"))
		{
			if (ImGui::Button("Unload"))
			{
				g_running = false;
			}
			ImGui::EndTabItem();
		}
	}
}
